model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    ckpt_path: "/mnt/fast/nobackup/users/jh00695/360HDR_LDM/models/first_stage_models/kl-f16/model.ckpt"
    embed_dim: 16
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 16
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 12
    #num_workers: 2
    train:
      target: ldm.data.ERPLight.ERPLightTrain
      params:
        data_root: "/mnt/fast/nobackup/users/jh00695/UTransformer/UTransformer-main/dataset"
        data_key: "LDR"
        size: 256
        ldr_dir: "/all_images/"
        hdr_dir: "/all_images_HDR/"
        env_map_dir: "/all_images_Env_Maps/"

    validation:
      target: ldm.data.ERPLight.ERPLightValidation
      params:
        data_root: "/mnt/fast/nobackup/users/jh00695/UTransformer/UTransformer-main/dataset"
        data_key: "LDR"
        size: 256
        ldr_dir: "/all_images/"
        hdr_dir: "/all_images_HDR/"
        env_map_dir: "/all_images_Env_Maps/"

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
